model: "osd"
network: "ro_34"
task: "snake"
resume: true
gpus: (0, )

train:
  optim: "adam"
  lr: 1e-4
  milestones: (80, 120, 150, 170)
  gamma: 0.5
  batch_size: 8
  dataset: "OsdTrain"
  num_workers: 1
  epoch: 150
test:
  dataset: "OsdMini"
  batch_size: 1

heads: { "ct_hm": 5, "wh": 2 }
segm_or_bbox: "segm"

evaluation:
  eval_ep: 1
